GET http://localhost:8080/app/
###
GET http://localhost:8080/admin/metrics
###
POST http://localhost:8080/admin/reset
###
GET http://localhost:8080/api/healthz
### fileserver 
GET http://localhost:8080/app/assets/logo.png
###
POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: "application/json"

{
  "body": "I had something interesting for breakfast"
}
###
POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: "application/json"

{
  "body": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
}

###
POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: "application/json"

{
  "body": "I hear Mastodon is better than Chirpy. sharbert I need to migrate",
  "extra": "this should be ignored"
}
###
POST http://localhost:8080/api/users HTTP/1.1
content-type: "application/json"

{
  "email": "gmartin9892@gmail.com",
  "password": "123askme"
}

###
POST http://localhost:8080/api/chirps HTTP/1.1
content-type: "application/json"
authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHktYWNjZXNzIiwic3ViIjoiMmFkZGUxZWItMDhkZC00NTdhLTkwMWUtZTE1ODQ2NmVmZmRmIiwiZXhwIjoxNzUzMDU0NjcwLCJpYXQiOjE3NTMwNTEwNzB9.Gl-qkJsgWcaNBz3mD_2-YaaT439tzo1eKinlsL7hKXc"

{
  "body": "If you're committed enough, you can make any story work."
}

###
GET http://localhost:8080/api/chirps HTTP/1.1
content-type: "application/json"

###
GET http://localhost:8080/api/chirps/d4412639-bf06-4467-88da-dc3118ad641f HTTP/1.1
content-type: "application/json"

###
POST http://localhost:8080/api/login HTTP/1.1
content-type: "application/json"

{
  "email": "saul@bettercall.com",
  "password": "123456"
}
###
POST http://localhost:8080/api/login HTTP/1.1
content-type: "application/json"

{
  "email": "gmartin9892@gmail.com",
  "password": "123askme"
}

###
POST http://localhost:8080/api/refresh HTTP/1.1
authorization: "Bearer d493f7244c4187ca70011708b646fc3f9b1534f977dad6dfa8e826449bbeb2fd2025"

